<a href="https://colab.research.google.com/github/ParnianH98/Heuristic-Implementation-of-8-puzzle/blob/main/H_as_total_displaced_numbers%2C_8_puzzle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
N = 3

input arbitrary puzzle using 0 instead of empty blanck

In [ ]:
arbitrary = []
while len(arbitrary) < 9:
  n = int(input("Enter:"))
  if (n in range(0,9)) and (n not in arbitrary):
    arbitrary.append(n)
  else:
    
    print("input 9 integers 0 to 8")

arbitrary = np.array(arbitrary)
puzzle = np.reshape(arbitrary,(3,3))
print(puzzle)
  

Enter:1
Enter:2
Enter:3
Enter:0
Enter:4
Enter:6
Enter:7
Enter:5
Enter:8
[[1 2 3]
 [0 4 6]
 [7 5 8]]


# **implement h1**

isSolvable

In [ ]:
def isSolvable(arbitrary):
  invCount = 0
  for i in range(8):
    for j in range(i+1,9):
      if (arbitrary[j]>arbitrary[i]) and (arbitrary[i]!=0):
        invCount+=1

  return (invCount%2 == 0)

computing number of dearangements

In [ ]:
def DarrangeNum(LIST):
  n = 0
  for i in range(9):
    a = LIST[i]
    if (a != 0)and (a != i+1):
      n+=1
  return n

returning four neighbours of a cell in the world :)

In [ ]:
def FindingStates(x,y):

  p1 = [x,y-1]
  p2 = [x,y+1]
  p3 = [x-1,y]
  p4 = [x+1,y]
  return [p1,p2,p3,p4]



returning possible neighbours of a cell in the puzzle

In [ ]:
def FindingPossibleStates(x,y,xforbid, yforbid):
  states = FindingStates(x,y)

  i=0
  while i<len(states):
    p = states[i]
    a = p[0]
    b = p[1]

    if (a < 0) or (a > N-1) or (b < 0) or (b > N-1) or (a == xforbid and b == yforbid):
      states.remove(p)
      i-=1
    i+=1
  return states


finding the minimum neighbour

In [ ]:
def FindingNextState(x,y,xforbid, yforbid,):
  states = FindingPossibleStates(x,y,xforbid, yforbid)
  global arbitrary
  global puzzle
  DAmax = 8
  FState = arbitrary.copy
  a = -1 
  b = -1 
  aa = -1 
  bb = -1

  for i in range(len(states)):
    p = states[i]
    a = p[0]
    b = p[1]
    newState = puzzle.copy()
    newState[x][y],newState[a][b] = newState[a][b], newState[x][y]
    newState = np.reshape(newState,(1,9))

    n = DarrangeNum(newState[0])
    if (n <= DAmax):
      DAmax = n
      FState = newState
      aa = a
      bb = b

  arbitrary = np.reshape(FState,(1,9))[0]
  puzzle = np.reshape(arbitrary,(3,3))
  print(puzzle)

  ##### 0 is now in (a,b) and has just replaced from (x,y)
  return [[aa,bb],[x,y]]


In [ ]:
global puzzle
global arbitrary
if isSolvable(arbitrary):

  #position of zero in the arbitrary
  loc = np.where(arbitrary == 0)
  loc = loc[0][0]

  #location of zero in the puzzle
  x = int(loc/3)
  y = int(loc%3)

  print(0)
  print(puzzle)

  xforbid = -1 
  yforbid = -1
  counter = 1
  n = DarrangeNum(arbitrary)
  while ( n > 0):
    print(counter)
    res = FindingNextState(x,y,xforbid, yforbid)
    x = res[0][0]
    y = res[0][1]
    xforbid = res[1][0]
    yforbid = res[1][1]
    n = DarrangeNum(arbitrary)
    counter+=1

else:
  print("not solvable!!")


0
[[1 2 3]
 [0 4 6]
 [7 5 8]]
1
[[1 2 3]
 [4 0 6]
 [7 5 8]]
2
[[1 2 3]
 [4 5 6]
 [7 0 8]]
3
[[1 2 3]
 [4 5 6]
 [7 8 0]]
